# Generated by Django 4.2.7 on 2023-11-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='title')),
                ('slug', models.SlugField(max_length=25, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='submenu')),
                ('slug', models.SlugField(max_length=40, verbose_name='slug')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='submenu', to='app.menu')),
            ],
            options={
                'verbose_name': 'submenu',
                'verbose_name_plural': 'submenus',
            },
        ),
    ]
