# Generated by Django 4.2.7 on 2023-11-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order_number',
            field=models.IntegerField(null=True, verbose_name='order number'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='order_number',
            field=models.IntegerField(null=True, verbose_name='order number'),
        ),
    ]
