# Generated by Django 4.2.7 on 2023-11-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_submenu_menu_alter_submenu_order_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submenu',
            unique_together={('title', 'order_number')},
        ),
    ]
