# Generated by Django 4.2.7 on 2023-11-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_submenu_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submenu',
            unique_together={('menu', 'order_number')},
        ),
    ]
