# Generated by Django 4.2.7 on 2023-11-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_submenu_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', related_query_name='submenu', to='app.menu'),
        ),
    ]
